#pragma once

#include <stddef.h>

#define IFENRIR_PROTOCOLO_VERSAO "ifenrir/1"
#define IFENRIR_SENTINELA "@IFENRIR@"
#define IFENRIR_SENTINELA_TAMANHO 9

#define IFENRIR_LIMITE_REQUISICAO_BYTES 1024
#define IFENRIR_LIMITE_RESPOSTA_BYTES 4096
#define IFENRIR_LIMITE_ID_CARACTERES 64
#define IFENRIR_LIMITE_TEXTO_ECO 128
#define IFENRIR_LIMITE_ROTULO 32
#define IFENRIR_LIMITE_DETALHE 96

typedef enum {
    IFENRIR_OK = 0,
    IFENRIR_ERRO_PROTOCOLO_INVALIDO,
    IFENRIR_ERRO_MENSAGEM_MALFORMADA,
    IFENRIR_ERRO_MENSAGEM_EXCEDE_LIMITE,
    IFENRIR_ERRO_CAMPO_OBRIGATORIO_AUSENTE,
    IFENRIR_ERRO_CAPACIDADE_DESCONHECIDA,
    IFENRIR_ERRO_CAPACIDADE_NAO_PERMITIDA,
    IFENRIR_ERRO_ARGUMENTO_INVALIDO,
    IFENRIR_ERRO_FALHA_INTERNA
} ifenrir_codigo_t;

const char *ifenrir_codigo_texto(ifenrir_codigo_t codigo);
